services:
  # Unified ML pipeline container
  mc-classifier:
    build:
      context: .
      dockerfile: Dockerfile
    image: mc_classifier:latest
    container_name: mc_classifier
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./experiments:/app/experiments
      - ./configs:/app/configs
    entrypoint: [ "python", "-m" ]
    command: [ "mc_classifier_pipeline.doc_retriever", "--help" ]
    tty: true
    working_dir: /app
