services:
  mc_pipeline:
    build:
      context: .
      dockerfile: Dockerfile            
    container_name: mc_pipeline

    env_file:
      - .env            

    volumes:
      - ./data:/app/data                 

    entrypoint: ["python", "-m", "mc_classifier_pipeline.doc_retriever"]
    command: ["--query", "election", "--start-date", "2024-12-01", "--end-date", "2024-12-31", "--limit", "10", "--output", "data/search_results.csv"]        

    # ports:
    #   - "8000:8000"          

    tty: true                
    working_dir: /app
