services:
  # Unified ML pipeline container
  mc-classifier:
    build:
      context: .
      dockerfile: Dockerfile
    image: mc_classifier:latest
    container_name: mc_classifier
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./experiments:/app/experiments
      - ./configs:/app/configs:ro
      - ./src:/app/src:ro
    command: ["mc_classifier", "doc_retriever", "--help"]
    tty: true
    working_dir: /app