version: "3.9"

services:
  mc_pipeline:
    build:
      context: .
      dockerfile: Dockerfile            
    container_name: mc_pipeline

    env_file:
      - .env            

    volumes:
      - ./data:/app/data                 

    entrypoint: ["python", "-m", "mc_classifier_pipeline.doc_retriever"]
    command: ["--help"]        

    # ports:
    #   - "8000:8000"          

    tty: true                
    working_dir: /app
