stages:
  count-words:
    cmd: python src/flexa/corpus_counter_script.py data/gutenberg_counts.csv data/gutenberg --case-insensitive
    deps:
    - src/flexa/corpus_counter_script.py
    - data/gutenberg
    outs:
    - data/gutenberg_counts.csv